---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../triton

patches:
  - target:
      kind: Deployment
      name: triton-server
    path: patch-deployment.yaml
  - target:
      kind: Deployment
      name: triton-server
    path: patch-gpu.yaml
