apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
spec:
  template:
    spec:
      containers:
        - name: triton-server
          resources:
            limits:
              nvidia.com/gpu: 1
