---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: triton-server
  labels:
    deployment: triton-server
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: triton-server
    weight: 100
  wildcardPolicy: None
