---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-triton
  annotations:
    openshift.io/display-name: "Demo - Triton"
    openshift.io/description: |
      A model serving example that uses source-to-image (s2i) from:
        - A Dockerfile
        - A specialized Builder Image using a source build from a git repository
    argocd.argoproj.io/sync-wave: "0"
