---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: triton-server
spec:
  lookupPolicy:
    local: true
  tags:
  - name: '24.08-py3'
    scheduled: true
    annotations:
      openshift.io/imported-from: nvcr.io/nvidia/tritonserver:25.04-py3
    from:
      kind: DockerImage
      name: nvcr.io/nvidia/tritonserver:25.04-py3
    referencePolicy:
      type: Local
  - name: latest
    from:
      kind: ImageStreamTag
      name: triton-server:25.04-py3
    referencePolicy:
      type: Local
